apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accumulo.fullname" . }}-client-properties
  namespace: {{ .Release.Namespace }}
data:
  accumulo-client.properties: |
    auth.type=password
    auth.principal=root
    instance.name={{ .Values.accumulo.instanceName }}
    instance.zookeepers={{ .Values.accumulo.zookeeper.address }}:{{ .Values.accumulo.zookeeper.port }}
    rpc.transport.idle.timeout={{ .Values.accumuloConfig.rpcTransportIdleTimeout }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accumulo.fullname" . }}-properties
  namespace: {{ .Release.Namespace }}
data:
  accumulo.properties: |
    general.rpc.timeout={{ .Values.accumuloConfig.rpcTimeout }}
    instance.secret={{ .Values.accumulo.instanceName }}
    instance.zookeeper.host={{ .Values.accumulo.zookeeper.address }}:{{ .Values.accumulo.zookeeper.port }}
    manager.wal.closer.implementation=org.apache.accumulo.server.manager.recovery.NoOpLogCloser
    table.durability={{ .Values.accumuloConfig.tableDurability }}
    tserver.memory.maps.native.enabled={{ .Values.accumuloConfig.tserverMemoryMapsNativeEnabled }}
    tserver.walog.max.size={{ .Values.accumuloConfig.tserverWalogMaxSize }}
    tserver.port.search={{ .Values.accumuloConfig.tserverPortSearch }}
    instance.volumes={{ .Values.accumuloConfig.volumes.default }},{{ .Values.accumuloConfig.volumes.logger }}
    general.volume.chooser={{ .Values.accumuloConfig.volumeChooser }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accumulo.fullname" . }}-logging
  namespace: {{ .Release.Namespace }}
data:
  log4j2-service.properties: |
    status = info
    dest = err
    name = AccumuloCompactorLoggingProperties
    appender.console.type = Console
    appender.console.name = STDOUT
    appender.console.target = SYSTEM_OUT
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{ISO8601} [%-8c{2}] %-5p: %m%n
    appender.console.filter.threshold.type = ThresholdFilter

